version: '3'
services:
  generators:
    container_name: craypc-generators
    image: dtr.dev.cray.com/pforce/generators:0.2.0 # TODO: change to dtr.dev.cray.com/craypc/generators:... when craypc pipeline is in place
    user: node
    command: "tail -f /dev/null"
    build:
      context: ../
      dockerfile: .craypc/dockerfiles/generators/Dockerfile
    networks:
      - craypc-generators
    volumes:
      - ${CRAYPC_VOLUME:-cray-generators}:/opt/cray-generators
      - /opt/cray-generators/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
  generators-swagger-codegen-cli:
    container_name: craypc-generators-swagger-codegen-cli
    image: dtr.dev.cray.com/pforce/generators-swagger-codegen-cli:2.4.1 # TODO: change to dtr.dev.cray.com/craypc/generators-swagger-codegen-cli:... when craypc pipeline is in place
    command: "tail -f /dev/null"
    build:
      context: ../
      dockerfile: .craypc/dockerfiles/generators-swagger-codegen-cli/Dockerfile
    networks:
      - craypc-generators
    volumes:
      - ${CRAYPC_VOLUME:-cray-generators}:/opt/cray-generators
networks:
  craypc-generators:
    driver: bridge
volumes:
  cray-generators:
    driver: local
