version: '3'
services:
  generators:
    container_name: craypc-generators
    image: ${CRAYPC_IMAGE_REPO}/generators:${CRAYPC_IMAGE_TAG}
    user: node
    command: "tail -f /dev/null"
    build:
      context: ../
      dockerfile: .craypc/dockerfiles/generators/Dockerfile
    networks:
      - craypc-generators
    volumes:
      - ${CRAYPC_LOCAL_PROJECT_PATH}:/opt/cray-generators
      - /opt/cray-generators/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
  generators-swagger-codegen-cli:
    container_name: craypc-generators-swagger-codegen-cli
    image: ${CRAYPC_IMAGE_REPO}/generators-swagger-codegen-cli:${CRAYPC_IMAGE_TAG}
    command: "tail -f /dev/null"
    build:
      context: ../
      dockerfile: .craypc/dockerfiles/generators-swagger-codegen-cli/Dockerfile
    networks:
      - craypc-generators
    volumes:
      - ${CRAYPC_LOCAL_PROJECT_PATH}:/opt/cray-generators
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  craypc-generators:
    driver: bridge
volumes:
  cray-generators:
    driver: local
