#!/bin/bash

exited_container=$(docker ps -a --filter name=^cray\-generators$ --filter status=exited --quiet)
if [ ! -z "$exited_container" ]; then
  docker rm cray-generators &> /dev/null
fi
if [ -z "$(docker ps -a --filter name=^cray\-generators$ --quiet)" ]; then
  docker build -f .container/Dockerfile -t cray/generators .
  docker run -t -d --name cray-generators \
    -v "$(pwd):/opt/cray-generators" \
    -v "/opt/cray-generators/node_modules" \
    cray/generators:latest /bin/sh
fi